# Generated by Django 4.2.6 on 2023-10-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
